<x-layout>

    <div class="page-heading header-text sub">
        <div class="container">
            <div class="row">

            </div>
        </div>
    </div>

    <div class="single-property section">
        <div class="container-fluid">
            <div class="row">
            
                <img src="{{ asset('assets/images/image11.png') }}" class="col-lg-7" alt="">

                <div class="col-lg-5">
                    <div class="info-table">
                        <ul>
                            <h5>
                                <strong>

                                    PROJECT ROADMAP
                                </strong>
                            </h5>
                            <h6>SOLAR PARTNERSHIP</h6>
                            <li>
                                <p>Based on this model, by 2025, all of Belize can be fossil fuel free.
                                    Financing for this program has been already secured in principle.</p>
                            </li>
                            <li>
                                <p>By utilizing only 40% of the lagoon surface area, a floating
                                    solar field can generate 100 Megawatts of peak power, which
                                    is currently the peak power load for the entire country.</p>
                            </li>
                            <li>
                                <p>At an average peak power production of 4 hours per day, over
                                    146GWh will be produced annually, which would fully cover
                                    Belize’s electricity purchased from Mexico and generated by
                                    fossil fuels during the day.</p>
                            </li>
                            <li>
                                <p>The Majority of the solar power will be used to power the
                                    Balam Reserve and other island projects and stored in
                                    batteries netting these projects at Carbon Negative.
                                    <strong>
                                        The large solar power supply will be ideally positioned to fascilitate a green
                                        (solar) crypto mining company
                                    </strong>
                                    In addition, excess solar would
                                </p>
                            </li>
                            <li>
                                <p>
                                    In addition, excess solar would also be used to generate and
                                    store green hydrogen for use in fuel cells for backup power
                                    and long-term storage. As power storage technologies are
                                    developed, the solar field can easily be expanded to 250
                                    Megawatts using only 50% of the lagoon and provide 100%
                                    replacement of Belize's current and future fossil fuel power
                                    generation.
                                </p>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="section best-deal">
        <div class="container-fluid">
            <div class="row">
                <div>
                    <div class="tabs-content">
                        <div class="row">
                            <div class="col-lg-10 mx-auto">
                                <div class="section-heading">
                                    <h6>| Project Roadmap</h6>
                                </div>
                                <div class="nav-wrapper ">
                                    <ul class="nav nav-tabs" role="tablist">
                                        <li class="nav-item" role="presentation">
                                            <button class="nav-link active" id="appartment-tab" data-bs-toggle="tab"
                                                data-bs-target="#appartment" type="button" role="tab"
                                                aria-controls="appartment" aria-selected="true">Phase 1: A</button>
                                        </li>
                                        <li class="nav-item" role="presentation">
                                            <button class="nav-link" id="villa-tab" data-bs-toggle="tab"
                                                data-bs-target="#villa" type="button" role="tab"
                                                aria-controls="villa" aria-selected="false">Phase2 B2+ Airport</button>
                                        </li>
                                        <li class="nav-item" role="presentation">
                                            <button class="nav-link" id="penthouse-tab" data-bs-toggle="tab"
                                                data-bs-target="#penthouse" type="button" role="tab"
                                                aria-controls="penthouse" aria-selected="false">Phase3 -L/F</button>
                                        </li>
                                        <li class="nav-item" role="presentation">
                                            <button class="nav-link" id="phase4-tab" data-bs-toggle="tab"
                                                data-bs-target="#phase4" type="button" role="tab"
                                                aria-controls="phase4" aria-selected="false">Phase 4: D</button>
                                        </li>
                                    </ul>
                                </div>
                                <div class="tab-content" id="myTabContent">
                                    <div class="tab-pane fade show active" id="appartment" role="tabpanel"
                                        aria-labelledby="appartment-tab">
                                        <div class="row">

                                            <ul>
                                                <li>
                                                    • 24 one-& two-bedroom homes on 9 acres private island @
                                                </li>
                                                <li>
                                                    • Conrad Net Zero Institute

                                                </li>
                                                <li>
                                                    • Boat Dock

                                                </li>
                                                <li>
                                                    • Infrastructure

                                                </li>
                                                <li>
                                                    • Fees/Permitting
                                                </li>
                                            </ul>

                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="villa" role="tabpanel"
                                        aria-labelledby="villa-tab">
                                        <div class="row">

                                            <ul>
                                                <li>
                                                    300-acresoceanfront/lagoonparcel 4-StarHotel
                                                </li>
                                                <li>
                                                    • 80 Hotel Villas
                                                </li>
                                                <li>
                                                    • 40 Villasin rentalpool
                                                </li>
                                                <li>
                                                    • 40 Additional Villas for sale
                                                </li>
                                                <li>
                                                    • 20Condominiumsforsale Healingandmedical
                                                </li>
                                                <li>
                                                    • Center 30-BerthMarina
                                                </li>
                                                <li>
                                                    • OrganicFarmand AquacultureCenter
                                                </li>

                                                <li>
                                                    • Host Village
                                                </li>
                                                <li>
                                                    • Mangrove Nursery
                                                </li>
                                                <li>
                                                    • Airstrip on site
                                                </li>
                                                <li>
                                                    • Floating Solar Park*
                                                </li>
                                                <li>
                                                    • *Financed separately TBD
                                                </li>
                                                <li>
                                                    • Marina #2
                                                </li>
                                            </ul>
                                            <div class="icon-button">
                                                <a href="#"><i class="fa fa-calendar"></i> Schedule a visit</a>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="phase4" role="tabpanel"
                                        aria-labelledby="phase4-tab">
                                        <div class="row">

                                            <ul>
                                                <li>
                                                    • 182 acres oceanfront parcel with 550
                                                </li>
                                                <li>
                                                    • Villas 305 rooms Hotel

                                                </li>
                                                <li>
                                                    • Golf Course
                                                </li>

                                            </ul>


                                            <div class="icon-button">
                                                <a href="#"><i class="fa fa-calendar"></i> Schedule a visit</a>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="penthouse" role="tabpanel"
                                        aria-labelledby="penthouse-tab">
                                        <div class="row">

                                            <ul>
                                                <li>
                                                    • ArtEco-Tech Village:645acreswith200Villasand200Condosforsale
                                                </li>
                                            </ul>
                                            <div class="icon-button">
                                                <a href="#"><i class="fa fa-calendar"></i> Schedule a visit</a>
                                            </div>

                                        </div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    <div class="featured section">
        <div class="container-fluid">
            <div class="row">



                <div class="col-lg-5">
                    <div class="section-heading">
                        <h6>| PROJECT ROADMAP</h6>
                    </div>
                    <div class="accordion" id="accordionExample">
                        <div class="accordion-item" style="padding: 10px; ">


                            <ul>
                                <h6>
                                    PHASE 2
                                </h6>
                                <li>• Art Eco-Tech Village:250 acres with 200 Villas and 200 Condos for sale <br></li>
                                <li>• Marina #2</li>
                                <li>• Solar Park 20-100 m/W</li>
                                <li></li>
                            </ul>





                            {{-- 
PHASE 3:
•
•
•
255 acres oceanfront parcel with 550 Villas
305 rooms Hotel
Golf Course --}}




                        </div>
                        <div class="accordion-item" style="padding: 10px; ">


                            <ul>
                                <h6>
                                    PHASE 3:
                                </h6>
                                <li>• 255 acres oceanfront parcel with 550 Villas</li>
                                <li>• 305 rooms Hotel</li>
                                <li>• Solar Park 20-100 m/W</li>
                                <li>• Golf Course</li>
                            </ul>

                        </div>
                    </div>

                </div>

                <div class="col-lg-7">
                    <div class="info-table">

                        <img src="{{ asset('assets/images/image12.png') }}" style="width: 100%; height: 400px;"
                            alt="" />

                    </div>
                </div>
            </div>
        </div>


        <div class="featured section">
            <div class="container-fluid">
                <div class="row">

                    <div class="col-lg-7">
                        <div class="info-table">

                            <img src="{{ asset('assets/images/image20.png') }}" style="width: 100%; height: 400px;"
                                alt="" />


                        </div>
                    </div>

                    <div class="col-lg-5">
                        <div class="section-heading">
                            <h6>| Balam Excape Resort & Residential Land Use Plan</h6>
                            <small>(2,200 Acres Development / 7,300 Acres Natinal Reserve)</small>
                        </div>
                        <div class="accordion" id="accordionExample">
                            <div class="accordion-item" style="padding: 10px; ">

                                <ul>
                                    <li>
                                        <span>A</span>
                                        Island Village (8 Acres)
                                    </li>
                                    <li>
                                        <span>A1</span>
                                        Marina Village (15 Acres)
                                    </li>
                                    <li>
                                        <span>A2</span>
                                        WaterFront Residential (30 Acres)
                                    </li>
                                    <li>
                                        <span>A3</span>
                                        WaterPark & Lagoon Villas (15 Acres)
                                    </li>
                                    <li>
                                        <span>B1</span>
                                        Resort Site (60 Acres)
                                    </li>
                                    <li>
                                        <span>B2</span>
                                        Resort Site (300 Acres)
                                    </li>
                                    <li>
                                        <span>B3</span>
                                        Waterfromt Residential (30 Acres)
                                       
                                    </li>
                                    <li>
                                        <span>C</span>
                                        Waterfromt Residential (33 Acres)
                                    </li>
                                    <li>
                                        <span>C1</span>
                                        Resort Site (32 Acres)
                                    </li>
                                    <li>
                                        <span>D</span>
                                        Approved 1,000 Acre subdivision 400 Residential lots / Commercial & Multifamily 
                                    </li>
                                    <li>
                                        <span>D1</span>
                                        Resort Site (32 Acres)
                                    </li>
                                    <li>
                                        <span>L/F</span>
                                        Lagoon Mixed Use Development (645 Acres): Golf Course
                                    </li>
                                </ul>

                            </div>
                        </div>

                    </div>
                </div>
            </div>




</x-layout>
